import restapiDocsRoutes from "@/routes/restapidocs";

export default [
  {
    path: "/settings/restapi-docs",
    component: () =>
      import("@/pages/Settings/Panels/Components/RestApiDocs.vue"),
    meta: { rbacViewName: "Setting", pageTitleKey: "SettingsRestAPIDocs" },
    children: restapiDocsRoutes,
  },
  {
    path: "/settings",
    name: "settings",
    component: () => import("@/pages/Settings/Main.vue"),
    meta: {
      rbacViewName: "Setting",
      pageTitleKey: "Settings",
      breadcrumb: [
        { label: "Home", link: "/" },
        { label: "System Settings", link: "/settings" },
      ],
    },
  },
  {
    path: "/settings/start",
    name: "settings-start",
    component: () => import("@/pages/Settings/Main.vue"),
    props: { start: true },
    meta: { rbacViewName: "Setting", pageTitleKey: "SettingsStart" },
  },
  {
    path: "/settings/system",
    name: "settings-system",
    component: () => import("@/pages/Settings/Main.vue"),
    props: { system: true },
    meta: { rbacViewName: "Setting", pageTitleKey: "SettingsSystem" },
  },
  {
    path: "/settings/security",
    name: "settings-security",
    component: () => import("@/pages/Settings/Main.vue"),
    props: { security: true },
    meta: { rbacViewName: "Setting", pageTitleKey: "SettingsSecurity" },
  },
  {
    path: "/settings/restapi",
    name: "settings-restapi",
    component: () => import("@/pages/Settings/Main.vue"),
    props: { restapi: true },
    meta: { rbacViewName: "Setting", pageTitleKey: "SettingsRestApi" },
  },
  {
    path: "/settings/credentials/:id?",
    name: "settings-credentials",
    component: () => import("@/pages/Settings/Main.vue"),
    props: { credentials: true },
    meta: { rbacViewName: "Setting", pageTitleKey: "SettingsCredentials" },
  },
  {
    path: "/settings/data-migration",
    name: "settings-data-migration",
    component: () => import("@/pages/Settings/Main.vue"),
    props: { importExport: true },
    meta: { rbacViewName: "Setting", pageTitleKey: "SettingsDataMigration" },
  },
  {
    path: "/settings/import-export",
    name: "settings-import-export",
    component: () => import("@/pages/Settings/Main.vue"),
    props: { importExport: true },
    meta: { rbacViewName: "Setting", pageTitleKey: "SettingsImportExport" },
  },
  {
    path: "/settings/debugging",
    name: "settings-debugging",
    component: () => import("@/pages/Settings/Main.vue"),
    props: { debugging: true },
    meta: { rbacViewName: "Setting", pageTitleKey: "SettingsDebugging" },
  },
  {
    path: "/settings/logs",
    name: "settings-logs",
    component: () => import("@/pages/Settings/Main.vue"),
    props: { logs: true },
    meta: { rbacViewName: "Setting", pageTitleKey: "SettingsLogs" },
  },
  {
    path: "/settings/scheduled-tasks",
    name: "settings-scheduledtasks",
    component: () => import("@/pages/Settings/Main.vue"),
    props: { scheduledTasks: true },
    meta: { rbacViewName: "Setting", pageTitleKey: "SettingsScheduledTasks" },
  },
  {
    path: "/settings/upgrade",
    name: "settings-upgrade",
    component: () => import("@/pages/Settings/Main.vue"),
    props: { upgrade: true },
    meta: { rbacViewName: "Setting", pageTitleKey: "SettingsUpgrade" },
  },
  {
    path: "/settings/update",
    name: "settings-update",
    component: () => import("@/pages/Settings/Main.vue"),
    props: { update: true },
    meta: { rbacViewName: "Setting", pageTitleKey: "SettingsUpdate" },
  },
  {
    path: "/settings/about",
    name: "settings-about",
    component: () => import("@/pages/Settings/Main.vue"),
    props: { about: true },
    meta: { rbacViewName: "Setting", pageTitleKey: "SettingsAbout" },
  },
];
