name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Describe the feature
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why is this needed?
    validations:
      required: true
