name: Question
description: Ask a question about rConfig
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        📘 Documentation:
        https://docs.rconfig.com

  - type: textarea
    attributes:
      label: Your question
    validations:
      required: true
