// iconImports.js
import { Icon } from '@iconify/vue';
import UserIcon from '@/pages/Shared/Icon/UserIcon.vue';
import NotificationIcon from '@/pages/Shared/Icon/NotificationIcon.vue';
import DashboardIcon from '@/pages/Shared/Icon/DashboardIcon.vue';
import InventoryIcon from '@/pages/Shared/Icon/InventoryIcon.vue';
import TasksIcon from '@/pages/Shared/Icon/TasksIcon.vue';
import ConfigToolsIcon from '@/pages/Shared/Icon/ConfigToolsIcon.vue';
import SettingsIcon from '@/pages/Shared/Icon/SettingsIcon.vue';
import SysLogViewerIcon from '@/pages/Shared/Icon/SysLogViewerIcon.vue';
import SysQueueManagerIcon from '@/pages/Shared/Icon/SysQueueManagerIcon.vue';
import ExternalLinkIcon from '@/pages/Shared/Icon/ExternalLinkIcon.vue';
import DeviceIcon from '@/pages/Shared/Icon/DeviceIcon.vue';
import CommandGroupIcon from '@/pages/Shared/Icon/CommandGroupIcon.vue';
import CommandsIcon from '@/pages/Shared/Icon/CommandsIcon.vue';
import TemplateIcon from '@/pages/Shared/Icon/TemplateIcon.vue';
import VendorIcon from '@/pages/Shared/Icon/VendorIcon.vue';
import TagIcon from '@/pages/Shared/Icon/TagIcon.vue';
import LogoutIcon from '@/pages/Shared/Icon/LogoutIcon.vue';
import CredentialsIcon from '@/pages/Shared/Icon/CredentialsIcon.vue';
import StatusGreenIcon from '@/pages/Shared/Icon/StatusGreenIcon.vue';
import StatusRedIcon from '@/pages/Shared/Icon/StatusRedIcon.vue';
import StatusYellowIcon from '@/pages/Shared/Icon/StatusYellowIcon.vue';
import StatusGrayIcon from '@/pages/Shared/Icon/StatusGrayIcon.vue';
import StarSelected from '@/pages/Shared/Icon/StarSelected.vue';
import StarUnselected from '@/pages/Shared/Icon/StarUnselected.vue';
import CommentAddIcon from '@/pages/Shared/Icon/CommentAddIcon.vue';
import NetworkDeviceIcon from '@/pages/Shared/Icon/NetworkDeviceIcon.vue';
import EmailIcon from '@/pages/Shared/Icon/EmailIcon.vue';

export { Icon, EmailIcon, StatusGreenIcon, StatusRedIcon, StatusYellowIcon, StatusGrayIcon, UserIcon, NotificationIcon, DashboardIcon, InventoryIcon, TasksIcon, ConfigToolsIcon, SettingsIcon, SysLogViewerIcon, SysQueueManagerIcon, ExternalLinkIcon, DeviceIcon, CommandGroupIcon, CommandsIcon, TemplateIcon, VendorIcon, TagIcon, LogoutIcon, CredentialsIcon, StarSelected, StarUnselected, CommentAddIcon, NetworkDeviceIcon };
